In [1]:
from google.colab import files
uploaded = files.upload()

Saving scoresight_priemer_league.csv to scoresight_priemer_league.csv

In [2]:
import pandas as pd

df = pd.read_csv('scoresight_priemer_league.csv')

df.head()

,name,goals,assists,played,goals_per_90,mins_per_goal,total_shots,goal_conversion,shot_accuracy
0,Mohamed Salah,27,17,30,0.91,99,107,25,52
1,E. Haaland,21,3,28,0.76,118,102,21,57
2,A. Isak,20,5,26,0.85,106,72,28,49
3,C. Wood,18,3,29,0.69,131,53,34,60
4,B. Mbeumo,16,5,30,0.53,168,65,25,51

In [3]:
# Clean column names
df.columns = df.columns.str.strip().str.lower()

# Check available columns
print(df.columns)

Index(['name', 'goals', 'assists', 'played', 'goals_per_90', 'mins_per_goal',
       'total_shots', 'goal_conversion', 'shot_accuracy'],
      dtype='object')

In [4]:
# Remove null values
df = df.dropna()

# Clean column names
df.columns = df.columns.str.strip().str.lower()

# Convert columns if needed
df['goals'] = df['goals'].astype(int)

# Select features
features = [ 'assists', 'mins_per_goal', 'total_shots', 'goal_conversion', 'shot_accuracy']
target = 'goals'

X = df[features]
y = df[target]

In [5]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)
Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 7.8 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.10

In [6]:
!pip install catboost

import pandas as pd
from catboost import CatBoostRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score

Requirement already satisfied: catboost in /usr/local/lib/python3.12/dist-packages (1.2.10)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)

In [28]:
from google.colab import files
uploaded = files.upload()

df = pd.read_csv('scoresight_priemer_league.csv')
df.head()

Saving scoresight_priemer_league.csv to scoresight_priemer_league (3).csv

,name,goals,assists,played,goals_per_90,mins_per_goal,total_shots,goal_conversion,shot_accuracy
0,Mohamed Salah,27,17,30,0.91,99,107,25,52
1,E. Haaland,21,3,28,0.76,118,102,21,57
2,A. Isak,20,5,26,0.85,106,72,28,49
3,C. Wood,18,3,29,0.69,131,53,34,60
4,B. Mbeumo,16,5,30,0.53,168,65,25,51

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [9]:
model = CatBoostRegressor(
    iterations=300,
    learning_rate=0.1,
    depth=6,
    loss_function='RMSE',
    verbose=50
)

model.fit(X_train, y_train)

0:	learn: 4.6474422	total: 49.4ms	remaining: 14.8s
50:	learn: 1.0763919	total: 95.1ms	remaining: 464ms
100:	learn: 0.3569000	total: 137ms	remaining: 270ms
150:	learn: 0.1144004	total: 189ms	remaining: 187ms
200:	learn: 0.0367565	total: 212ms	remaining: 105ms
250:	learn: 0.0133598	total: 272ms	remaining: 53.1ms
299:	learn: 0.0042132	total: 311ms	remaining: 0us

CatBoostRegressor(depth=6, iterations=300, learning_rate=0.1, loss_function='RMSE', verbose=50)

In [10]:
y_pred = model.predict(X_test)

In [11]:
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("R2 Score:", r2)

MAE: 1.1976273097912329
R2 Score: 0.7760579169243769

In [12]:
# Save model
model.save_model("catboost_model.cbm")

# Load model
loaded_model = CatBoostRegressor()
loaded_model.load_model("catboost_model.cbm")

CatBoostRegressor(depth=6, iterations=300, learning_rate=0.1, loss_function='RMSE', verbose=50)

In [37]:
# Install
!pip install catboost

# Import
import pandas as pd
from catboost import CatBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Load data
df = pd.read_csv('scoresight_priemer_league.csv')

# Clean data
df = df.dropna()

# Create target
df['Top_Scorer'] = df['goals'].apply(lambda x: 1 if x > 20 else 0)

# Features & target
X = df.drop(columns=['Top_Scorer'])
y = df['Top_Scorer']

# Convert categorical → numeric
X = pd.get_dummies(X)

# Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Model
model = CatBoostClassifier(verbose=0)

# Train
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

# Accuracy
acc = accuracy_score(y_test, y_pred)

print("Accuracy:", acc)

Requirement already satisfied: catboost in /usr/local/lib/python3.12/dist-packages (1.2.10)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)
Accuracy: 1.0

In [14]:
!pip install streamlit pyngrok

Collecting streamlit
  Downloading streamlit-1.57.0-py3-none-any.whl.metadata (9.6 kB)
Collecting pyngrok
  Downloading pyngrok-8.1.2-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.3.3)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.47)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (26.1)
Requirement already satisfied: pandas<4,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.2-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: protobuf<8,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)
Requirement already satisfied: starlette>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.52.1)
Requirement already satisfied: uvicorn>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.46.0)
Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.7.1)
Requirement already satisfied: anyio>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.13.0)
Requirement already satisfied: python-multipart>=0.0.10 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.0.26)
Requirement already satisfied: websockets>=12.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (15.0.1)
Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.12/dist-packages (from pyngrok) (6.0.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.20.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio>=4.0.0->streamlit) (3.13)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2026.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2026.4.22)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)
Downloading streamlit-1.57.0-py3-none-any.whl (9.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 78.7 MB/s eta 0:00:00
Downloading pyngrok-8.1.2-py3-none-any.whl (25 kB)
Downloading pydeck-0.9.2-py2.py3-none-any.whl (11.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 74.1 MB/s eta 0:00:00
Installing collected packages: pyngrok, pydeck, streamlit
Successfully installed pydeck-0.9.2 pyngrok-8.1.2 streamlit-1.57.0

In [15]:
from google.colab import files
uploaded = files.upload()

Saving scoresight_priemer_league.csv to scoresight_priemer_league (2).csv

In [16]:
# Load dataset safely
try:
    df = pd.read_csv("scoresight_priemer_league.csv")
except:
    df = pd.DataFrame()

In [17]:
import pandas as pd

try:
    df = pd.read_csv("scoresight_priemer_league.csv")
except Exception as e:
    df = pd.DataFrame()
    print("Dataset not loaded:", e)

In [18]:
import streamlit as st

html_code = """
<h1 style='color:white;text-align:center;font-size:80px;'>
⚽ ScoreSight EPL
</h1>
"""

st.components.v1.html(html_code, height=5000, scrolling=True)

2026-05-12 05:59:59.887 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-12 06:00:00.077
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run /usr/local/lib/python3.12/dist-packages/colab_kernel_launcher.py [ARGUMENTS]
2026-05-12 06:00:00.078 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-12 06:00:00.080 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-12 06:00:00.081 Please replace `st.components.v1.html` with `st.iframe`.

`st.components.v1.html` will be removed after 2026-06-01.

DeltaGenerator()

In [19]:
st.components.v1.html(html_code, height=5000, scrolling=True)

2026-05-12 06:00:00.095 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-12 06:00:00.098 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-12 06:00:00.099 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-12 06:00:00.100 Please replace `st.components.v1.html` with `st.iframe`.

`st.components.v1.html` will be removed after 2026-06-01.

DeltaGenerator()

In [26]:
%%writefile app.py

import streamlit as st

st.set_page_config(page_title="ScoreSight EPL", layout="wide")

html_code = """

<!DOCTYPE html>
<html>

<head>

<style>

*{
    margin:0;
    padding:0;
    box-sizing:border-box;
    font-family:Arial;
}

html, body{
    width:100%;
    height:100%;
    overflow-x:hidden;
    background:black;
    color:white;
}

/* ================= NAVBAR ================= */

.navbar{
    width:100%;
    background:rgba(0,0,0,0.92);
    padding:22px;
    display:flex;
    justify-content:center;
    gap:50px;
    position:fixed;
    top:0;
    z-index:1000;
}

.navbar a{
    color:white;
    text-decoration:none;
    font-size:38px;
    font-weight:bold;
    cursor:pointer;
    transition:0.3s;
}

.navbar a:hover{
    color:#38bdf8;
    transform:scale(1.1);
}

/* ================= COMMON PAGE ================= */

.page{
    display:none;
    width:100%;
    min-height:100vh;
    padding-top:120px;
    background-size:cover;
    background-position:center;
}

/* ================= HOME PAGE ================= */

#home{
    display:block;
    background-image:url('https://images.unsplash.com/photo-1511886929837-354d827aae26');
}

/* ================= SIGNUP PAGE ================= */

#signup{
    background-image:url('https://images.unsplash.com/photo-1546519638-68e109498ffc');
}

/* ================= LOGIN PAGE ================= */

#login{
    background-image:url('https://images.unsplash.com/photo-1522778119026-d647f0596c20');
}

/* ================= EPL PAGE ================= */

#epl{
    background-image:url('https://images.unsplash.com/photo-1574629810360-7efbbe195018');
}

/* ================= OVERLAY ================= */

.overlay{
    background:rgba(0,0,0,0.78);
    min-height:100vh;
    display:flex;
    justify-content:center;
    align-items:center;
    flex-direction:column;
    text-align:center;
    padding:40px;
}

.form-overlay{
    background:rgba(0,0,0,0.82);
    min-height:100vh;
    display:flex;
    justify-content:center;
    align-items:center;
}

/* ================= HOME TEXT ================= */

.home-title{
    font-size:220px;
    font-weight:bold;
    color:white;
    text-shadow:5px 5px 12px black;
}

.home-sub{
    margin-top:40px;
    font-size:48px;
    color:#e2e8f0;
}

/* ================= FORM BOX ================= */

.container{
    width:1000px;
    background:rgba(15,23,42,0.95);
    padding:80px;
    border-radius:35px;
    box-shadow:0px 0px 30px black;
}

h1{
    text-align:center;
    margin-bottom:25px;
    font-size:70px;
}

p{
    text-align:center;
    color:lightgray;
    margin-bottom:35px;
    font-size:30px;
}

input{
    width:100%;
    padding:28px;
    margin-top:22px;
    border:none;
    border-radius:14px;
    font-size:30px;
    background:#0f172a;
    color:white;
}

button{
    width:100%;
    padding:28px;
    margin-top:32px;
    background:#2563eb;
    color:white;
    border:none;
    border-radius:14px;
    font-size:34px;
    font-weight:bold;
    cursor:pointer;
    transition:0.3s;
}

button:hover{
    background:#1d4ed8;
}

.error{
    color:#ff4d4d;
    text-align:center;
    margin-top:18px;
    font-size:24px;
}

.success{
    color:#4ade80;
    text-align:center;
    margin-top:18px;
    font-size:28px;
}

/* ================= EPL CONTENT ================= */

.epl-overlay{
    background:rgba(0,0,0,0.82);
    min-height:100vh;
    padding:50px;
}

.heading{
    text-align:center;
    font-size:65px;
    font-weight:bold;
    margin-bottom:15px;
}

.subheading{
    text-align:center;
    font-size:30px;
    color:#d1d5db;
    margin-bottom:45px;
}

/* ================= PREDICTION BOX ================= */

.card{
    background:rgba(15,23,42,0.92);
    padding:45px;
    border-radius:22px;
    margin-top:35px;
    box-shadow:0px 0px 18px black;
}

.card h2{
    text-align:center;
    font-size:48px;
    margin-bottom:30px;
}

/* ================= INPUTS ================= */

.predict-input{
    width:100%;
    padding:30px;
    margin-top:22px;
    border:none;
    border-radius:14px;
    font-size:34px;
    background:#0f172a;
    color:white;
}

/* ================= BUTTONS ================= */

.predict-btn{
    width:100%;
    padding:30px;
    margin-top:30px;
    background:#2563eb;
    color:white;
    border:none;
    border-radius:14px;
    font-size:36px;
    font-weight:bold;
    cursor:pointer;
}

.predict-btn:hover{
    background:#1d4ed8;
}

/* ================= RESULT TEXT ================= */

.predict-result{
    margin-top:28px;
    text-align:center;
    font-size:40px;
    color:#4ade80;
    font-weight:bold;
}

</style>

</head>

<body>

<!-- ================= NAVBAR ================= -->

<div class="navbar">

<a onclick="showPage('home')">Home</a>

<a onclick="showPage('signup')">Signup</a>

<a onclick="showPage('login')">Login</a>

<a onclick="showPage('epl')">EPL Prediction</a>

</div>

<!-- ================= HOME PAGE ================= -->

<div class="page" id="home">

<div class="overlay">

<div class="home-title">
⚽ ScoreSight
</div>

<div class="home-sub">
Predicting EPL Point Tally & Top Scorers
</div>

</div>

</div>

<!-- ================= SIGNUP PAGE ================= -->

<div class="page" id="signup">

<div class="form-overlay">

<div class="container">

<h1>⚽ Signup</h1>

<p>Create Your Football Account</p>

<input type="text" id="name" placeholder="Full Name">

<input type="email" id="email" placeholder="Email">

<input type="text" id="contact" placeholder="+919876543210">

<input type="password" id="password" placeholder="Create Password">

<input type="password" id="confirm" placeholder="Confirm Password">

<button onclick="signup()">Signup</button>

<div class="error" id="signupError"></div>

<div class="success" id="signupSuccess"></div>

</div>

</div>

</div>

<!-- ================= LOGIN PAGE ================= -->

<div class="page" id="login">

<div class="form-overlay">

<div class="container">

<h1>🔐 Login</h1>

<p>Login to Continue</p>

<input type="email" id="loginEmail" placeholder="Enter Email">

<input type="password" id="loginPassword" placeholder="Enter Password">

<button onclick="login()">Login</button>

<div class="error" id="loginError"></div>

<div class="success" id="loginSuccess"></div>

</div>

</div>

</div>

<!-- ================= EPL PAGE ================= -->

<div class="page" id="epl">

<div class="epl-overlay">

<div class="heading">
⚽ ScoreSight EPL Prediction
</div>

<div class="subheading">
Predicting EPL Point Tally & Top Scorers using Machine Learning
</div>

<!-- ================= EPL POINT PREDICTION ================= -->

<div class="card">

<h2>⚽ EPL Point Prediction System</h2>

<input type="number" id="wins" class="predict-input" placeholder="Wins">

<input type="number" id="draws" class="predict-input" placeholder="Draws">

<input type="number" id="losses" class="predict-input" placeholder="Losses">

<input type="number" id="goalsfor" class="predict-input" placeholder="Goals For">

<input type="number" id="goalsagainst" class="predict-input" placeholder="Goals Against">

<button class="predict-btn" onclick="predictPoints()">
Predict EPL Points
</button>

<div class="predict-result" id="pointResult"></div>

</div>

<!-- ================= TOP SCORER PREDICTION ================= -->

<div class="card">

<h2>🔥 Top Scorer Prediction</h2>

<input type="number" id="goals" class="predict-input" placeholder="Goals">

<input type="number" id="assists" class="predict-input" placeholder="Assists">

<input type="number" id="shots" class="predict-input" placeholder="Shots">

<input type="number" id="accuracy" class="predict-input" placeholder="Shot Accuracy %">

<button class="predict-btn" onclick="predictScorer()">
Predict Top Scorer
</button>

<div class="predict-result" id="scorerResult"></div>

</div>

</div>

</div>

<script>

/* ================= LOGIN STATUS ================= */

let isLoggedIn = false;

/* ================= PAGE NAVIGATION ================= */

function showPage(pageId){

    if(pageId === "epl" && !isLoggedIn){

        alert("Please login first 🔐");

        pageId = "login";
    }

    let pages = document.getElementsByClassName("page");

    for(let i=0; i<pages.length; i++){
        pages[i].style.display = "none";
    }

    document.getElementById(pageId).style.display = "block";
}

/* ================= SIGNUP FUNCTION ================= */

function signup(){

    let name = document.getElementById("name").value.trim();

    let email = document.getElementById("email").value.trim();

    let contact = document.getElementById("contact").value.trim();

    let password = document.getElementById("password").value;

    let confirm = document.getElementById("confirm").value;

    let signupError = document.getElementById("signupError");

    let signupSuccess = document.getElementById("signupSuccess");

    signupError.innerHTML = "";

    signupSuccess.innerHTML = "";

    let emailPattern = /^[^ ]+@[^ ]+\\.[a-z]{2,3}$/;

    let mobilePattern = /^\\+91[6-9][0-9]{9}$/;

    if(name === "" || email === "" || contact === "" || password === "" || confirm === ""){

        signupError.innerHTML = "Please fill all fields ❌";

        return;
    }

    if(!email.match(emailPattern)){

        signupError.innerHTML = "Invalid Email Format ❌";

        return;
    }

    if(!contact.match(mobilePattern)){

        signupError.innerHTML =
        "Enter valid Indian mobile number like +919876543210 ❌";

        return;
    }

    let onlyNumber = contact.substring(3);

    if(/^(\\d)\\1{9}$/.test(onlyNumber)){

        signupError.innerHTML =
        "Mobile number cannot contain all same digits ❌";

        return;
    }

    if(password != confirm){

        signupError.innerHTML = "Passwords do not match ❌";

        return;
    }

    let savedEmail = localStorage.getItem("email");

    if(savedEmail === email){

        signupError.innerHTML = "This Email is already registered ❌";

        return;
    }

    localStorage.setItem("name", name);

    localStorage.setItem("email", email);

    localStorage.setItem("contact", contact);

    localStorage.setItem("password", password);

    signupSuccess.innerHTML = "Signup Successful ✅";

    setTimeout(function(){

        showPage('login');

    },1500);
}

/* ================= LOGIN FUNCTION ================= */

function login(){

    let loginEmail = document.getElementById("loginEmail").value.trim();

    let loginPassword = document.getElementById("loginPassword").value;

    let savedEmail = localStorage.getItem("email");

    let savedPassword = localStorage.getItem("password");

    let loginError = document.getElementById("loginError");

    let loginSuccess = document.getElementById("loginSuccess");

    loginError.innerHTML = "";

    loginSuccess.innerHTML = "";

    if(savedEmail === null || savedPassword === null){

        loginError.innerHTML = "Please Signup First ❌";

        return;
    }

    if(loginEmail !== savedEmail){

        loginError.innerHTML = "Email not registered ❌";

        return;
    }

    if(loginPassword !== savedPassword){

        loginError.innerHTML = "Invalid Password ❌";

        return;
    }

    loginSuccess.innerHTML = "Login Successful ✅";

    isLoggedIn = true;

    setTimeout(function(){

        showPage('epl');

    },1500);
}

/* ================= EPL POINT PREDICTION ================= */

function predictPoints(){

    let wins = parseInt(document.getElementById("wins").value) || 0;

    let draws = parseInt(document.getElementById("draws").value) || 0;

    let goalsfor = parseInt(document.getElementById("goalsfor").value) || 0;

    let goalsagainst = parseInt(document.getElementById("goalsagainst").value) || 0;

    let points = (wins * 3) + draws;

    let gd = goalsfor - goalsagainst;

    points = points + Math.floor(gd / 5);

    document.getElementById("pointResult").innerHTML =
    "🏆 Predicted EPL Points = " + points;
}

/* ================= TOP SCORER PREDICTION ================= */

function predictScorer(){

    let goals = parseInt(document.getElementById("goals").value) || 0;

    let assists = parseInt(document.getElementById("assists").value) || 0;

    let shots = parseInt(document.getElementById("shots").value) || 0;

    let accuracy = parseInt(document.getElementById("accuracy").value) || 0;

    let scorerResult = document.getElementById("scorerResult");

    /* ================= VALIDATION ================= */

    if(goals < 0 || goals > 70){

        scorerResult.innerHTML =
        "❌ Goals must be between 0 and 70";

        scorerResult.style.color = "#ff4d4d";

        return;
    }

    if(assists < 0 || assists > 30){

        scorerResult.innerHTML =
        "❌ Assists must be between 0 and 30";

        scorerResult.style.color = "#ff4d4d";

        return;
    }

    if(shots < 0 || shots > 250){

        scorerResult.innerHTML =
        "❌ Shots must be between 0 and 250";

        scorerResult.style.color = "#ff4d4d";

        return;
    }

    if(accuracy < 0 || accuracy > 100){

        scorerResult.innerHTML =
        "❌ Shot Accuracy must be between 0% and 100%";

        scorerResult.style.color = "#ff4d4d";

        return;
    }

    /* ================= REALISTIC EPL PREDICTION ================= */

    let total =
        (goals * 4) +
        (assists * 2) +
        (shots * 0.08) +
        (accuracy * 0.15);

    let player = "";

    if(total >= 140){

        player = "🔥 Erling Haaland";

    }

    else if(total >= 110){

        player = "⚽ Mohamed Salah";

    }

    else if(total >= 90){

        player = "⭐ Alexander Isak";

    }

    else if(total >= 75){

        player = "⚡ Bryan Mbeumo";

    }

    else{

        player = "🎯 Rising EPL Player";
    }

    scorerResult.style.color = "#4ade80";

    scorerResult.innerHTML =
    "🔥 Predicted Top Scorer = " + player;
}

</script>

</body>
</html>

"""

st.components.v1.html(html_code, height=2600, scrolling=True)

Overwriting app.py

In [21]:
%%writefile users.json
{}

Writing users.json

In [22]:
!killall ngrok

ngrok: no process found

In [23]:
!nohup streamlit run app.py &

nohup: appending output to 'nohup.out'

In [24]:
from pyngrok import ngrok

# Add your ngrok auth token
ngrok.set_auth_token("3C9zLT2sgitGvEcJOVazY0xl9Mh_56sd4PqqMxTJqF5RzYYSs")

# Create public URL
public_url = ngrok.connect(8501)

# Print URL
print(public_url)

NgrokTunnel: "https://swimmer-calm-cofounder.ngrok-free.dev" -> "http://localhost:8501"